server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka/
    healthcheck:
      enable: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: feign-rpc-server
