server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    healthcheck:
      enable: true
spring:
  application:
    name: feign-rpc-server
