spring:
  application:
    name: sleuth-zipkin-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  sleuth:
    enabled: false

# 在 zipkin.autoconfigure.storage.mysql.ZipkinMySQLStorageAutoConfiguration 这个里面 有使用这个配置的判断
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: 127.0.0.1:9300
