server:
  port: 8889
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka/
spring:
  application:
    name: feign-client
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000