server:
  port: 8889
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
spring:
  application:
    name: feign-client
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000