spring:
  application:
    name: sleuth-client
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0 # 设置样本收集率为1，即所有样本都收集
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
server:
  port: 9998
mybatis:
  mapper-locations: com.jaky.spring.cloud.sleuth.client.dao.*